-- AlterTable
ALTER TABLE "Stream" ADD COLUMN     "createAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "palyedTs" TIMESTAMP(3),
ADD COLUMN     "played" BOOLEAN NOT NULL DEFAULT false;
